# Generated by Django 3.1.4 on 2020-12-16 19:53

import api.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('email', models.CharField(max_length=50)),
                ('codemelli', models.CharField(max_length=10, unique=True, validators=[api.validators.codemeli])),
                ('m_name', models.CharField(max_length=200, validators=[api.validators.namfarsi])),
                ('m_email', models.CharField(max_length=50, validators=[api.validators.emailcheck])),
                ('m_mobile', models.CharField(max_length=20, validators=[api.validators.mobile])),
                ('p_name', models.CharField(max_length=200, validators=[api.validators.namfarsi])),
                ('p_email', models.CharField(max_length=50, validators=[api.validators.emailcheck])),
                ('p_mobile', models.CharField(max_length=20, validators=[api.validators.mobile])),
            ],
        ),
    ]
