# Generated by Django 3.1.4 on 2020-12-20 16:59

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201220_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='improve',
            field=models.CharField(blank=True, max_length=255, validators=[api.validators.namfarsi]),
        ),
        migrations.AlterField(
            model_name='manager',
            name='point',
            field=models.CharField(blank=True, max_length=255, validators=[api.validators.namfarsi]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='improve',
            field=models.CharField(blank=True, max_length=255, validators=[api.validators.namfarsi]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='point',
            field=models.CharField(blank=True, max_length=255, validators=[api.validators.namfarsi]),
        ),
    ]
