# Generated by Django 3.1.4 on 2020-12-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201220_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
