# Generated by Django 3.1.4 on 2020-12-27 20:13

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201220_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='m_uuid',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='p_uuid',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='improve',
            field=models.CharField(blank=True, max_length=255, validators=[api.validators.namOrnull]),
        ),
        migrations.AlterField(
            model_name='manager',
            name='point',
            field=models.CharField(blank=True, max_length=255, validators=[api.validators.namOrnull]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='improve',
            field=models.CharField(blank=True, max_length=255, validators=[api.validators.namOrnull]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='point',
            field=models.CharField(blank=True, max_length=255, validators=[api.validators.namOrnull]),
        ),
    ]
