# Generated by Django 3.1.4 on 2020-12-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201227_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='m_uuid',
            field=models.CharField(default='asd', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reference',
            name='p_uuid',
            field=models.CharField(default='asd', max_length=8),
            preserve_default=False,
        ),
    ]
