# Generated by Django 3.1.4 on 2020-12-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201227_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='m_uuid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reference',
            name='p_uuid',
            field=models.CharField(max_length=50),
        ),
    ]
